### PR TITLE
Now the Storage subclass provides the url() method

### PR DESCRIPTION
**Pull request by ogurtsov**
I wasn't really sure how to use backblaze apis to get the file url properly so I kept it simple.

### CODE REVIEW

**Comment by royendgel** [comment]
Yay! I will check this in the weekend and merge.

**Comment by metakermit** [comment]
Was this commit ever merged perhaps? I would also like to use the url field.

I also see that @amlatyrngom created another version that supports urls [here](https://github.com/amlatyrngom/django-b2storage). Perhaps it would be beneficial to consolidate the efforts and add the final project into django-storages.

**Comment by metakermit** [comment]
@royendgel I tested this patch in [my own fork](https://github.com/metakermit/django-backblazeb2-storage/tree/public-url) and I can confirm that it works, so it can be safely merged. Also, publishing it as a new package version would be helpful 🙂  In the mean time, you can use this as a dependency in *requirements.txt*:

```
-e git://github.com/metakermit/django-backblazeb2-storage.git@public-url#egg=django-backblazeb2-storage
```

Sample response I'm getting from my Django REST API:

```json
{
    "url": "https://www.facebook.com/events/726402504183732/",
    "img": "https://f001.backblazeb2.com/file/posterbat/events/2017/02/21/The20Mahones2028cdn29.jpg",
    "title": "The Mahones (cdn)",
    "start_time": "2017-02-21T19:00:00Z",
    "pk": 1266
}
```

For a Django REST framework serializer using the `img` field of a model defined as:

```
img = models.ImageField(null=True, blank=True, upload_to='events/%Y/%m/%d')
```

**Comment by royendgel** [comment]
it looks cool reviewed the code, looks good I will test it in the weekend , I will merge it right away sorry for delaying !

**Comment by metakermit** [comment]
Great, thanks @royendgel and @ogurtsov!

**Comment by moorchegue** [comment]
As far as I see this never made it to PyPI. Could you please release the new version?

**Pull request merged**
